version: '3.1'
services:
  cms-demo:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - '80:80'
    depends_on:
      - mongodb-demo
    environment:
      - mode=local
      - TZ=Asia/Hong_Kong
      - cdn_version=1.18
      - DB_PREFIX=mongodb
      - DB_HOST=mongodb-demo
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=db
      - DB_PORT=27017
      - PORT=80
    restart: always
    volumes:
      - ./backend:/usr/src/backend
  cms-frontend-demo:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - mongodb-demo
    environment:
      - PORT=3000
    restart: always
    volumes:
      - ./frontend:/usr/src/app/frontend
  mongodb-demo:
    image: mongo:5.0.2
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - "27017:27017"
    volumes:
      - db:/usr/src/db


networks:
  default:
    name: cms-demo
volumes:
  db: